Fix build issues on linux
esp-serial-flasher/port/wjwwood_serial_port.cpp:66:59: error: cannot bind non-const lvalue reference of type ‘serial::Timeout&’ to an rvalue of type ‘serial::Timeout’
   66 |     serial_port->setTimeout(serial::Timeout::simpleTimeout(timeout));

And a bunch of others due to mismatch between high_resolution_clock and steady_clock